# Generated by Django 6.0 on 2026-03-22 08:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_space_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('full', 'Full-time'), ('hourly', 'Hourly')], help_text='Full-time: all-day access | Hourly: time-slot based access', max_length=10)),
                ('start_date', models.DateField(default=datetime.date.today, help_text='Enrollment start date')),
                ('end_date', models.DateField(help_text='Enrollment end date (inclusive)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this enrollment currently active?')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for this enrollment (calculated from pricing)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(blank=True, help_text='Auto-assigned seat (do not select manually)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='study_space_management.seat')),
                ('student', models.ForeignKey(help_text='Student being enrolled', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='study_space_management.student')),
                ('study_space', models.ForeignKey(help_text='Study space where student will study', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='study_space_management.studyspace')),
                ('time_slot', models.ForeignKey(blank=True, help_text='Required for hourly membership only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='study_space_management.timeslot')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('membership_type', 'full')), fields=('seat',), name='unique_active_full_time_seat'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('membership_type', 'hourly')), fields=('seat', 'time_slot'), name='unique_active_hourly_seat_slot')],
            },
        ),
    ]
