# Generated by Django 6.0 on 2026-03-22 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_management', '0001_initial'),
        ('study_space_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_active_full_time_seat',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_active_hourly_seat_slot',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='booking_type',
            field=models.CharField(choices=[('hourly', 'Hourly (specific hours)'), ('daily', 'Daily (any hours within open time)'), ('weekly', 'Weekly (fixed hours per day)'), ('monthly', 'Monthly (unlimited)'), ('custom', 'Custom (admin defined)')], default='hourly', help_text='Type of booking: hourly, daily, weekly, monthly, or custom', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='custom_end_time',
            field=models.TimeField(blank=True, help_text='For custom hourly bookings: end time', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom total price (overrides all calculations)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='custom_start_time',
            field=models.TimeField(blank=True, help_text='For custom hourly bookings: start time', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Comma-separated days: 0,1,2,3,4 (Mon-Fri)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='hours_per_day',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours per day commitment (e.g., 1.5 for 1.5 hours)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For daily: price per day', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For hourly/daily: price per hour', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For monthly: price per month', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For weekly: price per week', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(help_text='Enrollment end date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='study_space_management.seat'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(help_text='Enrollment start date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='study_space_management.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='study_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='study_space_management.studyspace'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='For hourly bookings: select the time slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='study_space_management.timeslot'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated total amount', max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_type', 'hourly'), ('is_active', True), ('time_slot__isnull', False)), fields=('seat', 'start_date', 'time_slot'), name='unique_hourly_time_slot_booking'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_type', 'daily'), ('is_active', True)), fields=('seat', 'start_date'), name='unique_daily_booking'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='membership_type',
        ),
    ]
