# Generated by Django 6.0 on 2026-03-23 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_management', '0003_alter_enrollment_booking_type_and_more'),
        ('study_space_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_hourly_time_slot_booking',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='custom_end_time',
            field=models.TimeField(blank=True, help_text='For hourly bookings: end time', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='custom_start_time',
            field=models.TimeField(blank=True, help_text='For hourly bookings: start time', null=True),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_type', 'hourly'), ('is_active', True)), fields=('seat', 'start_date', 'custom_start_time'), name='unique_hourly_booking'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='time_slot',
        ),
    ]
