# Generated by Django 6.0 on 2026-03-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_management', '0004_remove_enrollment_unique_hourly_time_slot_booking_and_more'),
        ('study_space_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_hourly_booking',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='custom_end_time',
            field=models.TimeField(blank=True, help_text='For hourly bookings: end time (e.g., 12:00:00)', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom total price (overrides all calculations)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='custom_start_time',
            field=models.TimeField(blank=True, help_text='For hourly bookings: start time (e.g., 10:00:00)', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Comma-separated days: 0=Mon,1=Tue,2=Wed,3=Thu,4=Fri,5=Sat,6=Sun', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this enrollment currently active?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Has the enrollment been fully paid?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per day (locked at enrollment)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per hour (locked at enrollment)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per month (locked at enrollment)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='price_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per week (locked at enrollment)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='seat',
            field=models.ForeignKey(blank=True, help_text='Assigned seat (auto-assigned if left blank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='study_space_management.seat'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(help_text='Student enrolled', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='study_space_management.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='study_space',
            field=models.ForeignKey(help_text='Study space selected', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='study_space_management.studyspace'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_type', 'hourly'), ('custom_start_time__isnull', False), ('is_active', True)), fields=('seat', 'start_date', 'custom_start_time'), name='unique_hourly_booking'),
        ),
    ]
