# Generated by Django 6.0 on 2026-03-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the study space (e.g., 'Main Hall', 'Computer Lab')", max_length=100, unique=True)),
                ('location', models.CharField(blank=True, help_text='Physical location or building details', max_length=200)),
                ('capacity', models.PositiveIntegerField(help_text='Total number of seats available in this space')),
                ('is_active', models.BooleanField(default=True, help_text='Is this study space currently available for enrollment?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Study Space',
                'verbose_name_plural': 'Study Spaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the student', max_length=100)),
                ('mobile', models.CharField(db_index=True, help_text='10-digit mobile number', max_length=15)),
                ('aadhaar_number', models.CharField(help_text='12-digit Aadhaar number (unique)', max_length=20, unique=True)),
                ('father_name', models.CharField(help_text="Student's father's full name", max_length=100)),
                ('father_mobile', models.CharField(help_text="Father's contact number", max_length=15)),
                ('course_name', models.CharField(help_text='Course enrolled in (e.g., B.Tech, MBA)', max_length=100)),
                ('institute_name', models.CharField(help_text='College/Institute name', max_length=150)),
                ('date_of_joining', models.DateField(help_text='Date when student joined the study space')),
                ('student_image', models.ImageField(blank=True, help_text="Student's photograph", null=True, upload_to='students/')),
                ('aadhaar_front', models.ImageField(blank=True, help_text='Aadhaar card front side', null=True, upload_to='students/')),
                ('aadhaar_back', models.ImageField(blank=True, help_text='Aadhaar card back side', null=True, upload_to='students/')),
                ('permanent_address', models.TextField(help_text='Permanent home address')),
                ('local_address', models.TextField(help_text='Current/local address')),
                ('active', models.BooleanField(default=True, help_text='Soft delete flag - set False to deactivate student')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-date_of_joining'],
                'indexes': [models.Index(fields=['mobile'], name='study_space_mobile_eb2c19_idx'), models.Index(fields=['name'], name='study_space_name_337493_idx'), models.Index(fields=['active'], name='study_space_active_ee597e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text="Seat identifier (e.g., 'A1', 'B12', 'Desk-5')", max_length=20)),
                ('seat_type', models.CharField(choices=[('standard', 'Standard Desk'), ('premium', 'Air Conditioned Desk')], default='standard', help_text='Type of seat (for pricing or preference)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this seat available for enrollment?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_space', models.ForeignKey(help_text='Which study space this seat belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='study_space_management.studyspace')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['study_space', 'seat_number'],
                'unique_together': {('study_space', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General Slot', help_text="e.g., 'Morning', 'Afternoon', 'Evening'", max_length=50)),
                ('start_time', models.TimeField(help_text='Start time (e.g., 09:00:00)')),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text='Duration in hours (e.g., 3.0 = 3 hours)', max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in Gantt chart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_space', models.ForeignKey(help_text='Which study space this time slot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='study_space_management.studyspace')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['study_space', 'display_order', 'start_time'],
                'unique_together': {('study_space', 'start_time')},
            },
        ),
    ]
